# Generated by Django 3.2.23 on 2024-05-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_zoomtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoomtoken',
            old_name='access_key',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='zoomtoken',
            old_name='secret_key',
            new_name='client_secret',
        ),
    ]
