# Generated by Django 3.2.23 on 2024-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20240503_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
