# Generated by Django 3.2.23 on 2024-05-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_alter_zoomtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoomtoken',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
