# Generated by Django 3.2.23 on 2024-04-24 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_doctor_specialized'),
        ('push_notifications', '0006_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.appointment'),
        ),
    ]
