# Generated by Django 3.2.23 on 2024-04-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0007_alter_notification_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='Notification_type',
        ),
    ]
