# Generated by Django 3.2.23 on 2024-05-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0009_notification_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_api_key', to='push_notifications.onesignalapp'),
        ),
        migrations.AddField(
            model_name='notification',
            name='app_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_app_id', to='push_notifications.onesignalapp'),
        ),
    ]
