# Generated by Django 3.2.23 on 2024-05-08 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0009_notification_notification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='onesignal_app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='push_notifications.onesignalapp'),
        ),
    ]
