# Generated by Django 3.2.23 on 2024-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0010_auto_20240502_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
