# Generated by Django 3.2.23 on 2024-05-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0011_alter_notification_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='app_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='app',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
