# Generated by Django 3.2.23 on 2024-05-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0012_auto_20240502_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='app',
            new_name='app_id',
        ),
    ]
