# Generated by Django 3.2.23 on 2024-05-06 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0013_rename_app_notification_app_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='app_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_app_id', to='push_notifications.onesignalapp'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_api_key', to='push_notifications.onesignalapp'),
        ),
    ]
