# Generated by Django 3.2.23 on 2024-05-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0014_auto_20240506_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='app',
        ),
        migrations.AddField(
            model_name='notification',
            name='app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
