# Generated by Django 3.2.23 on 2024-05-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0015_auto_20240506_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='app_id',
        ),
    ]
