# Generated by Django 3.2.23 on 2024-04-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_doctor_specialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='join_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
