# Generated by Django 3.2.23 on 2024-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20240430_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
