# Generated by Django 3.2.23 on 2024-05-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_appointment_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zoom',
        ),
    ]
