# Generated by Django 3.2.23 on 2024-05-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_appointment_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='topic',
        ),
    ]
